version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: future_management_db
    environment:
      POSTGRES_DB: future_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: future_management_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fm-network
  api:
    build:
      context: ../../server
      dockerfile: ../../infrastructure/docker/Dockerfile.api
    container_name: feature-api
    environment:
      - db_host=postgres
      - db_user=postgres
      - db_password=future_management_db
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - fm-network

  ui:
    build:
      context: ../../sdk/javascript
      dockerfile: ../../infrastructure/docker/Dockerfile.ui
    container_name: feature-ui
    depends_on:
      - api
    networks:
      - fm-network
  nginx:
    image: nginx:alpine
    container_name: feature-nginx
    ports:
      - "80:80"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
      - ui
    networks:
      - fm-network

volumes:

  postgres_data:

networks:
  fm-network:
    driver: bridge
